### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by valent** [mxaddict/mmaker#2]
On running the bot, am getting this error> the definition of the function "privatePostPositions" is missing  
[TypeError] this.exchange.privatePostPositions is not a function
Kindly rectify.

**Comment by mxaddict** [comment]
Can you post the conf you are using?

**Comment by mxaddict** [comment]
I see, in another issue you posted that you were trying to get it to work with a different exchange.

As stated in the README, I have not yet added support for other exchanges.

So, I will be closing this issue.
