### ISSUE TITLE
how to change the exchange for the algo?

### ISSUE THREAD

**Issue by nateflanders** [mxaddict/mmaker#4]
You mentioned in the readme how binance is currently default, but any exchange within CCXT can be connected. 

Do you have any instruction on that change within your code? 

Looking to connect Bitmex. 

Sorry if noob question. Just need direction as to where to start, and I'll be off to the races. 

Thanks! 

@mxaddict

**Comment by nateflanders** [comment]
nvm found the config to change bitmex params and currency to BTC/USD rather than what I assumed XBT/USD 

However, getting the error when running: 

` [InvalidOrder] bitmex {"error":{"message":"orderQty is invalid","name":"HTTPError"}}
                       
                           at handleErrors   ccxt/js/bitmex.js:1233            throw new exact[message] (feedback);                                            
                           at then           ccxt/js/base/Exchange.js:628      this.handleErrors (response.status, response.statusText, url, method, responseH…
                           at _tickCallback  internal/process/next_tick.js:68                                                                         `


Am I going to go line by line in the engine.js file under src to match mex calls? 

If not, do you have any guidance here? 

Thank you @mxaddict

**Comment by mxaddict** [comment]
> nvm found the config to change bitmex params and currency to BTC/USD rather than what I assumed XBT/USD
> 
> However, getting the error when running:
> 
> ` [InvalidOrder] bitmex {"error":{"message":"orderQty is invalid","name":"HTTPError"}}
> 
> ```
>                        at handleErrors   ccxt/js/bitmex.js:1233            throw new exact[message] (feedback);                                            
>                        at then           ccxt/js/base/Exchange.js:628      this.handleErrors (response.status, response.statusText, url, method, responseH…
>                        at _tickCallback  internal/process/next_tick.js:68                                                                         `
> ```
> 
> Am I going to go line by line in the engine.js file under src to match mex calls?
> 
> If not, do you have any guidance here?
> 
> Thank you @mxaddict

I think if I remember correctly there were some API calls that I updated/added that were no longer cross exchange and need to be refactored to work with other exchanges.

**Comment by mxaddict** [comment]
@nateflanders let's continue discussion of #5 on this issue as they are related.

**Comment by mxaddict** [comment]
I'll see if I can update the API calls to be cross exchange again, not sure if it's worth the effort though.

I was planning on revamping the entire code base for this project.
