### ISSUE TITLE
Invalidorder bitmex orderQty is invalid http error

### ISSUE THREAD

**Issue by nateflanders** [mxaddict/mmaker#5]
Got bitmex connected, but keep receiving the repeating error below: 

`oor@toor-VirtualBox:~/mmaker$ ./mmaker.js
8/26/2019 6:51:23 AM | COLORS ENABLED
8/26/2019 6:51:23 AM | Using Exchange "bitmex"
8/26/2019 6:51:25 AM | Using Market "BTC/USD"
8/26/2019 6:51:26 AM | price bid/ask/spread %          | asset balance start/current | currency start/current | asset p/l value/% | currency p/l value/%  | overall p/l %     | orders size/buy/sell
                       -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                       USD +10,337/+10,337.50/+00.005% | BTC +0.03016809/+0.03016809 | USD 0/+311.85          | BTC 0/00.000%     | USD +311.85/Infinity% | BTC/USD Infinity% | BTC 0/0/0           
8/26/2019 6:51:26 AM | [InvalidOrder] bitmex {"error":{"message":"orderQty is invalid","name":"HTTPError"}}
                       
                           at handleErrors   ccxt/js/bitmex.js:1233            throw new exact[message] (feedback);                                            
                           at then           ccxt/js/base/Exchange.js:628      this.handleErrors (response.status, response.statusText, url, method, responseH…
                           at _tickCallback  internal/process/next_tick.js:68

**Comment by nateflanders** [comment]
@mxaddict

**Comment by mxaddict** [comment]
closing this as it's related to #4
